// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsUWuEHcGkbo3bc7ws3bOq0uByOpxIR2k',
    appId: '1:622099091971:web:341ac9e225686942177436',
    messagingSenderId: '622099091971',
    projectId: 'expense-e451a',
    authDomain: 'expense-e451a.firebaseapp.com',
    storageBucket: 'expense-e451a.firebasestorage.app',
    measurementId: 'G-XSDZDL9BRF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk9fgXOVuJx-O42HE8lgNy0XFLC1TSXvE',
    appId: '1:622099091971:android:b0f3b79660ff9979177436',
    messagingSenderId: '622099091971',
    projectId: 'expense-e451a',
    storageBucket: 'expense-e451a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz1_CqY-slFIsKU_xgdlQX_94Ot2KCdLo',
    appId: '1:622099091971:ios:518b5aa7aad62cf2177436',
    messagingSenderId: '622099091971',
    projectId: 'expense-e451a',
    storageBucket: 'expense-e451a.firebasestorage.app',
    iosClientId: '622099091971-n860u1ka2l10a7fn77d9foh4uf4sq227.apps.googleusercontent.com',
    iosBundleId: 'com.example.practice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz1_CqY-slFIsKU_xgdlQX_94Ot2KCdLo',
    appId: '1:622099091971:ios:518b5aa7aad62cf2177436',
    messagingSenderId: '622099091971',
    projectId: 'expense-e451a',
    storageBucket: 'expense-e451a.firebasestorage.app',
    iosClientId: '622099091971-n860u1ka2l10a7fn77d9foh4uf4sq227.apps.googleusercontent.com',
    iosBundleId: 'com.example.practice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsUWuEHcGkbo3bc7ws3bOq0uByOpxIR2k',
    appId: '1:622099091971:web:5893d3870cc4e51b177436',
    messagingSenderId: '622099091971',
    projectId: 'expense-e451a',
    authDomain: 'expense-e451a.firebaseapp.com',
    storageBucket: 'expense-e451a.firebasestorage.app',
    measurementId: 'G-Z0Y3QG5NW5',
  );
}
